### ISSUE TITLE
Error:(18, 24) error: cannot find symbol variable savedstanceState

### ISSUE THREAD

**Issue by tymiles003** [tonytran1/Whisk#1]
Tried to generate a signed key with android studio and received this message.

C:\Users\tom\Desktop\whisk\Whisk-master\app\src\main\java\com\example\team3\whisk\UserSettingActivity.java

Error:(18, 24) error: cannot find symbol variable savedstanceState

**Comment by tonytran1** [comment]
This project is no longer being worked on at this moment. So the old code and keys are now depreciated.
